config/routes.rb
Rails.application.routes.draw do

  root to: 'guests#index'
  devise_for :users
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  # after_create :sign_up_for_mailing_list #todo

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/index.html.erb
<% provide(:title, "Home") %>

<h1>Demo</h1>
<p>This is a sample app using Devise + roles.</p>

<% if user_signed_in? %>
  <h3>Welcome <%= current_user.name %>!</h3>
  <% if current_user.admin? %>
    <h3>Admin's stuff:</h3>
    <p><%= link_to 'User count:', users_path %> <%= User.count %></p>
  <% else %>
    <h3>You've signed up. Cool.</h3>
  <% end %>
<% else %>
  <h3>Sign up and be cool.</h3>
  <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-large' %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
      <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>
<% end %>
</p>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devise + roles demo | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->
</head>
<body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
</body>
</html>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<% provide(:title, "Users Index") %>

<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Show User") %>

<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>